# Generated by Django 5.1.1 on 2024-09-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('body', models.CharField(max_length=255)),
                ('manufactor', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('brand new', 'Brand New'), ('quite new', 'Quite New'), ('used', 'Used')], default='brand new', max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('kilometers', models.IntegerField()),
                ('horse_power', models.IntegerField()),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WellcomeHerro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('background_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
